### ISSUE TITLE
Error in Test

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-students/cartoon-collections-online-web-ft-061019#1]
```
    it "returns false if all calls are 4 characters or less" do
<<<<<<< HEAD
      calls_short = ["wind", "fire", "tree", "axe", "code"]
      expect(long_planeteer_calls(calls_short)).to eq(false)
=======
    calls_short = ["wind", "fire", "tree", "axe", "code"]
    expect(long_planeteer_calls(calls_short)).to eq(false)
>>>>>>> 1367bb9... Updates spec description
    end
```

This block causes the test to error out and confuses students. Easy fix to delete these lines. :)

@drakeltheryuujin

**Comment by drakeltheryuujin** [comment]
Hi there,
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 
When raising issues, make sure to open them in the associated repository in `learn-co-curriculum`.
Thanks for contributing! 💙
